/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.DatabasController;
import Controller.ModelController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import Model.Tasks;
import Model.Case;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author petter
 */
public class CaseAndTask extends javax.swing.JFrame {

    static ModelController mc = new ModelController();
    static String arendeNr;
    static boolean caseStatus;

    /**
     * Creates new form ArendeAndTask
     */
    public CaseAndTask() {
        initComponents();
        loadMeny();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        meny = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMessages1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMessages2 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        registerCase1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        registerCase2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMessages = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        registerCase3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        caseTasks = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        modifyCase1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMessages3 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMessages4 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Välkommen till Fiktiv ABs ärendehanteringssystem.");

        jButton1.setText("Registrera ärende");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Uppdatera ärende");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Attestera arbetsuppgift");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblMessages1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMessages1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMessages1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMessages1);

        tblMessages2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMessages2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMessages2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblMessages2);

        jLabel29.setText("Ärenden");

        jLabel30.setText("Arbetsuppgifter");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ej avslutade ärenden");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menyLayout = new javax.swing.GroupLayout(meny);
        meny.setLayout(menyLayout);
        menyLayout.setHorizontalGroup(
            menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menyLayout.createSequentialGroup()
                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menyLayout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(menyLayout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox1))
                                    .addGroup(menyLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton3)))
                                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(menyLayout.createSequentialGroup()
                            .addGap(224, 224, 224)
                            .addComponent(jLabel1))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        menyLayout.setVerticalGroup(
            menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menyLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(36, 36, 36)
                .addGroup(menyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel30)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Registrera ärende");

        jLabel3.setText("Ärende nr:");

        jLabel4.setText("---");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Instruktioner:");

        jLabel6.setText("Kategori:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nätverk", "Applikationer", "Säkerhet", "Användare" }));

        jButton4.setText("Avbryt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nästa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerCase1Layout = new javax.swing.GroupLayout(registerCase1);
        registerCase1.setLayout(registerCase1Layout);
        registerCase1Layout.setHorizontalGroup(
            registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase1Layout.createSequentialGroup()
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCase1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerCase1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jLabel2)))
                    .addGroup(registerCase1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(registerCase1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(registerCase1Layout.createSequentialGroup()
                                    .addComponent(jButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        registerCase1Layout.setVerticalGroup(
            registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        registerCase2.setPreferredSize(new java.awt.Dimension(850, 542));

        tblMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMessages);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Registrera arbetsuppgifter");

        jLabel8.setText("Ärendenr:");

        jLabel9.setText("---");

        jLabel10.setText("Uppgift:");

        jLabel11.setText("Tidsbudget");

        jLabel12.setText("Arbetsuppgifter för ärendet");

        jButton6.setText("Lägg till");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Nästa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Avbryt");

        javax.swing.GroupLayout registerCase2Layout = new javax.swing.GroupLayout(registerCase2);
        registerCase2.setLayout(registerCase2Layout);
        registerCase2Layout.setHorizontalGroup(
            registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(registerCase2Layout.createSequentialGroup()
                        .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10))
                            .addGroup(registerCase2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(10, 10, 10)))
                        .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jTextField2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCase2Layout.createSequentialGroup()
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerCase2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(registerCase2Layout.createSequentialGroup()
                        .addContainerGap(384, Short.MAX_VALUE)
                        .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(registerCase2Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        registerCase2Layout.setVerticalGroup(
            registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCase2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerCase2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(25, 25, 25))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Summering");

        jLabel14.setText("Ärendenummer:");

        jLabel15.setText("Kategori:");

        jLabel16.setText("Antal arbetsuppgofter:");

        jLabel17.setText("Total tidsbudget:");

        jLabel18.setText("---");

        jLabel19.setText("---");

        jLabel20.setText("---");

        jLabel21.setText("---");

        caseTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(caseTasks);

        jLabel22.setText("Ärendets arbetsuppgifter");

        jLabel23.setText("Instruktioner");

        jButton9.setText("Huvudmeny");

        javax.swing.GroupLayout registerCase3Layout = new javax.swing.GroupLayout(registerCase3);
        registerCase3.setLayout(registerCase3Layout);
        registerCase3Layout.setHorizontalGroup(
            registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCase3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField3)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
            .addGroup(registerCase3Layout.createSequentialGroup()
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCase3Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel13))
                    .addGroup(registerCase3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerCase3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel18))
                            .addGroup(registerCase3Layout.createSequentialGroup()
                                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)))
                            .addGroup(registerCase3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel19))))
                    .addGroup(registerCase3Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jButton9)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        registerCase3Layout.setVerticalGroup(
            registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCase3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerCase3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(4, 4, 4))
        );

        modifyCase1.setPreferredSize(new java.awt.Dimension(850, 542));

        jButton10.setText("Uppdatera");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nätverk", "Applikationer", "Användare", "Säkerhet" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktiv", "Påbörjad", "Avslutad" }));

        jLabel25.setText("Kategori:");

        jLabel26.setText("Status: ");

        jLabel27.setText("Arbetsuppgifter: ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Uppdatera ärende:");

        tblMessages3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMessages3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMessages3MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblMessages3);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("---");

        jLabel32.setText("Instruktion:");

        tblMessages4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(tblMessages4);

        jLabel24.setText("Uppgift:");

        jLabel33.setText("Tidsbudget:");

        jButton11.setText("Lägg till uppgift");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktiv", "Påbörjad", "Avslutad" }));

        jLabel34.setText("Tidsbudget:");

        jLabel35.setText("Uppgift:");

        jLabel36.setText("Personal:");

        jButton12.setText("Uppdatera uppgift");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel38.setText("Status: ");

        jLabel37.setText("Förbrukad tid:");

        javax.swing.GroupLayout modifyCase1Layout = new javax.swing.GroupLayout(modifyCase1);
        modifyCase1.setLayout(modifyCase1Layout);
        modifyCase1Layout.setHorizontalGroup(
            modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyCase1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyCase1Layout.createSequentialGroup()
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(79, 79, 79)
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addContainerGap(490, Short.MAX_VALUE))
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11)
                                .addGap(102, 102, 102))))
                    .addGroup(modifyCase1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addGap(89, 89, 89))
                    .addGroup(modifyCase1Layout.createSequentialGroup()
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(modifyCase1Layout.createSequentialGroup()
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(84, 84, 84)
                                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(modifyCase1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel32))
                                    .addGroup(modifyCase1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)
                                        .addComponent(jButton10))))
                            .addComponent(jLabel27)
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)))
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(modifyCase1Layout.createSequentialGroup()
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifyCase1Layout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12))
                            .addComponent(jLabel38))
                        .addGap(100, 100, 100))))
        );
        modifyCase1Layout.setVerticalGroup(
            modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyCase1Layout.createSequentialGroup()
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addGap(1, 1, 1)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37))
                .addGap(15, 15, 15)
                .addGroup(modifyCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(meny, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registerCase3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modifyCase1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(meny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(meny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerCase2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(modifyCase1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );

        jMenu2.setText("File");

        jMenuItem1.setText("Meny");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Registrera ärende");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem5.setText("Avsluta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //registrera ärende-knappen på menysidan
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadRegisterCase1();    
    }//GEN-LAST:event_jButton1ActionPerformed
    //Updatera ärendeknappen på menysidan
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadUpdateCase1();
        jLabel31.setText(arendeNr);
        loadCaseListUpdatePage();
        int caseNr = Integer.parseInt(arendeNr);
        loadTaskListUpdatePage(caseNr);
    }//GEN-LAST:event_jButton2ActionPerformed
    //Attestera arbetsuppgift på menysidan
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            int rowNr = tblMessages2.getSelectedRow();
//            String name = tblMessages2.getValueAt(rowNr,8).toString();
            int taskNr = Integer.parseInt(tblMessages2.getValueAt(rowNr,0).toString());
            int id = Integer.parseInt(tblMessages2.getValueAt(rowNr,1).toString());
            
                    String attest = JOptionPane.showInputDialog(rootPane, "skriv under med ditt namn:");
                    if(attest == null){
                       JOptionPane.showMessageDialog(rootPane, "Avbruten"); 
                    }else{
                    DatabasController cc;
                    cc = new DatabasController();
                    cc.attestTask(taskNr, attest);
                    loadTaskListMenyPage(id);
                    }
        
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att attestera arbetsuppgiften");
                System.out.println(ex.getMessage());
        }
        catch(Exception e) {System.out.println(e);}
                    
                    
    }//GEN-LAST:event_jButton3ActionPerformed
    //Menyknappen i menyn
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        loadMeny();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //Registrera ärende i menyn
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        loadRegisterCase1();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    //Avslutaknappen i menyn
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    //Avbrytknapp på registerCase1
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        meny.setVisible(true);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        modifyCase1.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

   //Nästa knappen på RegisterCase1
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            DatabasController cc;   
            cc = new DatabasController();
            
            arendeNr = jLabel4.getText();
            String instructions = jTextArea1.getText();
            String category = (String)jComboBox1.getSelectedItem();
            String caseStatus = "Aktiv";
            mc.regCase(arendeNr, instructions, category, caseStatus);
            cc.saveCaseToDatabase(arendeNr, category, instructions, caseStatus);
            registerCase1.setVisible(false);
            registerCase2.setVisible(true);
            jTextArea1.setText("");
            loadRegisterCase2();
        } catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Databasfel");
                System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    //lägg till knapp på registerCase2
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String taskDesc = jTextField1.getText();
            String tid = jTextField2.getText();
            if(taskDesc.equals("")){
               JOptionPane.showMessageDialog(rootPane, "Uppgiften får inte vara blank!");
            }
            else if(tid.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Tid får inte vara blank!");
            }
            else{
                   DatabasController cc;
                   cc = new DatabasController();
                   
              
                   double timeBudget = Double.parseDouble(tid);
                   int taskNr = cc.getNewTaskNr();
                   String uppgStatus = "aktiv";
                   int caseNr = Integer.parseInt(arendeNr);   
                   cc.addTaskToDatabase(taskNr, caseNr, taskDesc, timeBudget, uppgStatus);
                   
                   List <Tasks> taskList = new ArrayList<>();
                   taskList = cc.getTasksforCase(caseNr);
                   
                   int row=0; 
                   int rows = taskList.size();
                   Object[][] data = new Object[rows][4];
                   
                   for (Tasks ts : taskList){
                   data[row][0] = ts.getTaskNr();
                   data[row][1] = ts.getCaseNr();
                   data[row][2] = ts.getDescription();
                   data[row][3] = ts.getTimebudget();
                   row++;
                   }
                   
                   DefaultTableModel tblModel = new DefaultTableModel(data, Constants.TASKS_TABLE_HEADER);
                   tblMessages.setModel(tblModel);
                   tblMessages.setShowGrid(true);
                   jTextField1.setText("");
                   jTextField2.setText("");
                   
            }
            
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Databasfel");
                System.out.println(ex.getMessage());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Fel format på tid");
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    // nästa knapp i registerCase2 
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           loadRegisterCase3();
           
    }//GEN-LAST:event_jButton7ActionPerformed
    //Uppdateraknappen på uppdaterasidan
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            int caseNr = Integer.parseInt(arendeNr);
            String category = (String)jComboBox2.getSelectedItem();
            String caseStat = (String)jComboBox3.getSelectedItem();
            String instructions = jTextField4.getText();
            DatabasController cc = new DatabasController();
            cc.updateCase(caseNr, category, caseStat, instructions);
            loadCaseListUpdatePage();
            
            
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att uppdatera ärendet");
                System.out.println(ex.getMessage());
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        if (jCheckBox1.isSelected()) {
            caseStatus = true;
        }
        else {
            caseStatus = false;
        }
        loadCaseListMenyPage();
    }//GEN-LAST:event_jCheckBox1MouseClicked
    //När ärende markerats på förstasidan
    private void tblMessages1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMessages1MouseClicked
        int rowNr = tblMessages1.getSelectedRow();
        int id = Integer.parseInt(tblMessages1.getValueAt(rowNr,0).toString());     
        jButton2.setEnabled(true);
        loadTaskListMenyPage(id);
        arendeNr = Integer.toString(id);
    }//GEN-LAST:event_tblMessages1MouseClicked
    //Lägg till uppgiftsknapp på uppdateraärendesidan.
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
        String taskDesc = jTextField5.getText();
        String tid = jTextField6.getText();
        if(taskDesc.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Uppgiften får inte vara blank!");
        }
        else if(tid.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Tid får inte vara blank!");
        }
        else{
            DatabasController cc;
            cc = new DatabasController();
				   
            double timeBudget = Double.parseDouble(tid);
            int taskNr = cc.getNewTaskNr();
            String uppgStatus = "Aktiv";
            int caseNr = Integer.parseInt(arendeNr);   
            cc.addTaskToDatabase(taskNr, caseNr, taskDesc, timeBudget, uppgStatus);
            loadTaskListUpdatePage(caseNr);
	}
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att uppdatera ärendet");
                System.out.println(ex.getMessage()); 
        }
    }//GEN-LAST:event_jButton11ActionPerformed
    //Listan med tasks på updatesidan
    private void tblMessages3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMessages3MouseClicked
       jButton12.setEnabled(true); 
       int rowNr = tblMessages3.getSelectedRow();
       jTextField7.setText(tblMessages3.getValueAt(rowNr,2).toString());
       jTextField8.setText((tblMessages3.getValueAt(rowNr,3).toString()));
       jTextField9.setText((tblMessages3.getValueAt(rowNr,4).toString()));
       jTextField10.setText((tblMessages3.getValueAt(rowNr,5).toString()));
    }//GEN-LAST:event_tblMessages3MouseClicked
    //Uppdatera task på updatesidan
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try{
        int rowNr = tblMessages3.getSelectedRow();
        int taskNr = Integer.parseInt(tblMessages3.getValueAt(rowNr,0).toString());
        String pers = jTextField7.getText();
        int persNr = Integer.parseInt(pers);
        String taskDesc = jTextField8.getText();
        String taskStat = (String)jComboBox4.getSelectedItem();
        String tid = jTextField9.getText();
        double timeBudget = Double.parseDouble(tid);
        String tidAnv = jTextField10.getText();
        double timeUsed = Double.parseDouble(tidAnv);
               
        DatabasController cc;
        cc = new DatabasController();
        cc.updateTask(taskNr, persNr, taskDesc, timeBudget, timeUsed, taskStat);
        
        int id = Integer.parseInt(tblMessages3.getValueAt(0,1).toString());
        loadTaskListUpdatePage(id);
        jButton12.setEnabled(false);
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att uppdatera uppgiften");
                System.out.println(ex.getMessage()); 
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tblMessages2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMessages2MouseClicked
        jButton3.setEnabled(true);
        
    }//GEN-LAST:event_tblMessages2MouseClicked
    
    
    private void loadRegisterCase1(){
        meny.setVisible(false);
        registerCase1.setVisible(true);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        modifyCase1.setVisible(false);
        
        //Skriver ut nästa ärendenumret på skärmen
        try {
            DatabasController cc = new DatabasController();
            int nextNr = cc.getNewCaseNr();
            arendeNr = Integer.toString(nextNr);
            jLabel4.setText(arendeNr);
             
                  
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta nytt nr.");
                System.out.println(ex.getMessage());
            
        }
    }
        
    private void loadRegisterCase2(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(true);
        registerCase3.setVisible(false);
        modifyCase1.setVisible(false);
        jLabel9.setText(arendeNr);
        
        
    }
    
    private void loadRegisterCase3(){
        
            meny.setVisible(false);
            registerCase1.setVisible(false);
            registerCase2.setVisible(false);
            registerCase3.setVisible(true);
            modifyCase1.setVisible(false);
         
            
          try {  
            DatabasController cc;
            cc = new DatabasController();
            jLabel18.setText(arendeNr); //Skriver ut ärendenumret på skärmen
           
   
            cc.getTasksforCase(Integer.parseInt(arendeNr)); 
               
        } catch (SQLException ex) {
            Logger.getLogger(CaseAndTask.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    private void loadUpdateCase1(){
        meny.setVisible(false);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        modifyCase1.setVisible(true);
        jButton12.setEnabled(false);
    }
    

    
    private void loadMeny(){
        
        try{
        meny.setVisible(true);
        registerCase1.setVisible(false);
        registerCase2.setVisible(false);
        registerCase3.setVisible(false);
        modifyCase1.setVisible(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        if (jCheckBox1.isSelected()) {
            caseStatus = true;
        }
        else {
            caseStatus = false;
        }
        loadCaseListMenyPage();
        } catch (Exception ex){
                System.out.println(ex.getMessage());
            
    }
    }
    //Metod för att ladda listan med tasks på uppdaterasidan
    private void loadTaskListUpdatePage(int id){
        try{
            DatabasController cc = new DatabasController();
            List <Tasks> taskList = new ArrayList<>();
            taskList = cc.getDetailedTasks(id);
            
            int row=0; 
            int rows = taskList.size();
            Object[][] data = new Object[rows][9];
            
            for (Tasks ts : taskList){
                   data[row][0] = ts.getTaskNr();
                   data[row][1] = ts.getCaseNr();
                   data[row][2] = ts.getPersonalNr();
                   data[row][3] = ts.getDescription();
                   data[row][4] = ts.getTimebudget();
                   data[row][5] = ts.getTimeUsed();
                   data[row][6] = ts.getTaskStatus();
                   data[row][7] = ts.getComment();
                   data[row][8] = ts.getAttestedBy();
                   row++;
                   }
            DefaultTableModel tblModel = new DefaultTableModel(data, Constants.FULL_TASKS_TABLE_HEADER);
                   tblMessages3.setModel(tblModel);
                   tblMessages3.setShowGrid(true);
                   
           
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta arbetsuppgifter för valt ärende");
                System.out.println(ex.getMessage());
    }
    }
    
    //Metod för att ladda listan med arbetsuppgifter på menysidan
    private void loadTaskListMenyPage(int id){
        try{
            DatabasController cc = new DatabasController();
            List <Tasks> taskList = new ArrayList<>();
            taskList = cc.getDetailedTasks(id);
            
            int row=0; 
            int rows = taskList.size();
            Object[][] data = new Object[rows][9];
            
            for (Tasks ts : taskList){
                   data[row][0] = ts.getTaskNr();
                   data[row][1] = ts.getCaseNr();
                   data[row][2] = ts.getPersonalNr();
                   data[row][3] = ts.getDescription();
                   data[row][4] = ts.getTimebudget();
                   data[row][5] = ts.getTimeUsed();
                   data[row][6] = ts.getTaskStatus();
                   data[row][7] = ts.getComment();
                   data[row][8] = ts.getAttestedBy();
                   row++;
                   }
            DefaultTableModel tblModel = new DefaultTableModel(data, Constants.FULL_TASKS_TABLE_HEADER);
                   tblMessages2.setModel(tblModel);
                   tblMessages2.setShowGrid(true);
                   
           
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta arbetsuppgifter för valt ärende");
                System.out.println(ex.getMessage());
    }
    } 
    //Ladda data på ärendetabellen i uppdaterasidan
    private void loadCaseListUpdatePage(){
        try{
            DatabasController cc = new DatabasController();
            List <Case> caseList = new ArrayList<>();
            caseList = cc.getCase(arendeNr);
            
            int row=0; 
            int rows = caseList.size();
            Object[][] data = new Object[rows][4];
            
            for (Case cs : caseList){
                   data[row][0] = cs.getCaseNr();
                   data[row][1] = cs.getCategory();
                   data[row][2] = cs.getCaseStatus();
                   data[row][3] = cs.getInstructions();
                   row++;
                   }
            DefaultTableModel tblModel = new DefaultTableModel(data, Constants.CASE_TABLE_HEADER);
                   tblMessages4.setModel(tblModel);
                   tblMessages4.setShowGrid(true);
            
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta ärenden");
                System.out.println(ex.getMessage());
    }
    }
    
    //Metod för att ladda listan med ärenden på menysidan
    private void loadCaseListMenyPage(){
        try{
            DatabasController cc = new DatabasController();
            List <Case> caseList = new ArrayList<>();
            caseList = cc.getCases(caseStatus);
            
            int row=0; 
            int rows = caseList.size();
            Object[][] data = new Object[rows][4];
            
            for (Case cs : caseList){
                   data[row][0] = cs.getCaseNr();
                   data[row][1] = cs.getCategory();
                   data[row][2] = cs.getCaseStatus();
                   data[row][3] = cs.getInstructions();
                   row++;
                   }
            DefaultTableModel tblModel = new DefaultTableModel(data, Constants.CASE_TABLE_HEADER);
                   tblMessages1.setModel(tblModel);
                   tblMessages1.setShowGrid(true);
            
        }catch (SQLException ex){JOptionPane.showMessageDialog(rootPane, "Det gick inte att hämta ärenden");
                System.out.println(ex.getMessage());
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseAndTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseAndTask().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable caseTasks;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel meny;
    private javax.swing.JPanel modifyCase1;
    private javax.swing.JPanel registerCase1;
    private javax.swing.JPanel registerCase2;
    private javax.swing.JPanel registerCase3;
    private javax.swing.JTable tblMessages;
    private javax.swing.JTable tblMessages1;
    private javax.swing.JTable tblMessages2;
    private javax.swing.JTable tblMessages3;
    private javax.swing.JTable tblMessages4;
    // End of variables declaration//GEN-END:variables
}
